### PR TITLE
Bump to phf v0.11

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by benesch** [comment]
Thanks for the approval, @djc! Do you have the merge and release bits here?

**Comment by djc** [comment]
Oops, sorry! Will have to check if this is in a releasable state (what the next version should be etc), if you have an opportunity to help out with that, would be great!

**Comment by benesch** [comment]
Yeah! What specifically can I help with? The only other change on main since v0.6.1 is the bump to 2022a; scanning the changelog, looks like there are plenty of minor releases that include tzdata bumps. And since bumping phf to v0.11 is an internal only change, should be safe to release the current main as v0.6.2.

**Comment by djc** [comment]
Okay, sounds good. If you have the opportunity, a PR that bumps the version number and updates the changelog would be awesome (bonus points for retroactively including 0.6.1 entries).

**Comment by benesch** [comment]
On it!

**Pull request merged**
