### PR TITLE
Disable default features in chrono-tz-build

### LINKED ISSUE #103: `case-insensitive` feature in `chrono-tz` is not propagated to `chrono-tz-build`
Despite being optional in `chrono-tz`, the `case-insensitive` feature is not disabled in `chrono-tz-build`.

`chrono-tz-build` unconditionally pulls in `uncased` even if `chrono-tz` is built without the feature enabled.

### PR DESCRIPTION
**Pull request by lopopolo**
Fixes #103.

### CODE REVIEW

**Comment by lopopolo** [comment]
I know this is a small change, but I'd very much appreciate it if this could be included in a patch release soon if it is accepted.

**Comment by djc** [comment]
Does this change cause semver-incompatible API changes?

**Comment by lopopolo** [comment]
I am not sure. The uncased feature in chrono-tz still requires a feature. I'm not sure what the implications are for that feature in the build script.

**Comment by lopopolo** [comment]
It looks like the build crate still emits the cfg directives so this change should not result in any new APIs becoming available.

**Comment by djc** [comment]
I don't see how this changes anything, since chrono-tz-build doesn't enable any features by default as far as I can see?

**Comment by lopopolo** [comment]
Ahh I think you're right. Maybe it was the reshuffling of the phf features that fixed things up

**Pull request closed without merging**
