### PR TITLE
Close #121

### LINKED ISSUE #121: Turn `ParseError` into a real error
Currently it's just a `String`, this is unidiomatic for various reasons:
- It doesn't implement `std::error::Error`, meaning `?` or any kind of error coercion isn't possible (i.e with anyhow)
- It doesn't give enough info on what the error is going to be, the documentation could give this info but that's not ideal
- It's an unexpected API
- It might be unnecessary allocation (converting an error to string isn't always necessary)
- It doesn't allow polymorphism or fields

### PR DESCRIPTION
**Pull request by laralove143**

### CODE REVIEW

**Comment by djc** [comment]
This mostly looks good. Can you please give the existing commit a meaningful commit message, and add a comment that bumps the version number for chrono-tz because this is a semver-incompatible change?

**Comment by laralove143** [comment]
I don't know how to edit a commit message after a push

**Comment by djc** [comment]
Well, you could have googled it. Try `git rebase -i main` and put an `r` (for `reword`) next to both of your commits. It should bring up your editor for both commits, move the commit message on the second commit to the first commit and change the second commit to something like "Bump version for semver-incompatible changes".

**Comment by pitdicker** [comment]
I'd like to reopen this PR. It was closed because the author deleted his fork of the repo.

But I'm not a fan of enums that change depending on the crate features. And we should especially not remove the `Copy` implementation when the `std` feature is enabled.

@djc Does it give any benefit to include the string that failed to parse? It is passed to `from_str` by reference so the user can easily wrap it with something like anyhows `with_context`.

**Comment by djc** [comment]
Leaving the string out of seems reasonable.

**Pull request closed without merging**
