### PR TITLE
2024a

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by pitdicker** [comment]
Nice! Are you subscribed to the mailing list to get the notification for a new version? Or did you just notice?

**Comment by djc** [comment]
I'm subscribed to tz-announce -- this actually got released 11 days ago, so I'm not particularly timely.

**Comment by pitdicker** [comment]
I'll also subscribe, maybe I can beat you to it next time :smile:.

**Comment by djc** [comment]
Would be great!

**Pull request merged**
