### PR TITLE
Iter all timezones

### PR DESCRIPTION
**Pull request by samoylovfp**

### CODE REVIEW

**Comment by NilsIrl** [comment]
Fix #8

**Comment by Lesiuk** [comment]
What keeps us from merging it? I would love to see this change released.

**Comment by NilsIrl** [comment]
> What keeps us from merging it? I would love to see this change released.

A reviewer

**Comment by NilsIrl** [comment]
@quodlibetor

**Comment by quodlibetor** [comment]
Hi, sorry I have been missing. If you add a test demonstrating the functionality I would be happy to merge this!

**Comment by samoylovfp** [comment]
No worries, thanks for maintaining this!

There is a one-line doctest included, is this enough?
https://github.com/chronotope/chrono-tz/pull/42/files#diff-b4aea3e418ccdb71239b96952d9cddb6R151

**Comment by samoylovfp** [comment]
Done. Please feel free to do any changes you deem necessary to merge this

**Comment by samoylovfp** [comment]
@quodlibetor fixed the build issue, please review again

**Comment by quodlibetor** [comment]
Thanks!

**Pull request merged**
