### PR TITLE
Bump to 0.9.1 with 2024b

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by pitdicker** [comment]
I'll have a look later today.

**Comment by djc** [comment]
If you want to stop reviewing, that's also fine, just let me know!

**Comment by pitdicker** [comment]
> If you want to stop reviewing, that's also fine, just let me know!

I am doing way less than I feel like I should for chrono. Feel free to ask/cc me anytime!
Got more busy unfortunately.

**Comment by pitdicker** [comment]
With this release the TZDB starts to use `%z` instead of numerical time zone names such as `+01`. We have no code to handle this.

It seems to me the cleanest solution is to the time zone optional with the `None` case representing the special `%z`, and adding some extra code to the formatting method that uses the stuff from `FixedOffset`. What do you think?

**Comment by pitdicker** [comment]
Before:
```rust
            Tz::Africa__Asmara => {
                const REST: &[(i64, FixedTimespan)] = &[
                    (-1946168836, FixedTimespan { utc_offset: 9000, dst_offset: 0, name: "+0230" }),
                    (-1309746600, FixedTimespan { utc_offset: 10800, dst_offset: 0, name: "EAT" }),
                    (-1261969200, FixedTimespan { utc_offset: 9000, dst_offset: 0, name: "+0230" }),
                    (-1041388200, FixedTimespan { utc_offset: 9900, dst_offset: 0, name: "+0245" }),
                    (-865305900, FixedTimespan { utc_offset: 10800, dst_offset: 0, name: "EAT" }),
                ];
                FixedTimespanSet {
                    first: FixedTimespan {
                        utc_offset: 8836,
                        dst_offset: 0,
                        name: "LMT",
                    },
                    rest: REST
                }
            },
```

After:
```rust
            Tz::Africa__Asmara => {
                const REST: &[(i64, FixedTimespan)] = &[
                    (-1946168836, FixedTimespan { utc_offset: 9000, dst_offset: 0, name: "%z" }),
                    (-1309746600, FixedTimespan { utc_offset: 10800, dst_offset: 0, name: "EAT" }),
                    (-1261969200, FixedTimespan { utc_offset: 9000, dst_offset: 0, name: "%z" }),
                    (-1041388200, FixedTimespan { utc_offset: 9900, dst_offset: 0, name: "%z" }),
                    (-865305900, FixedTimespan { utc_offset: 10800, dst_offset: 0, name: "EAT" }),
                ];
                FixedTimespanSet {
                    first: FixedTimespan {
                        utc_offset: 8836,
                        dst_offset: 0,
                        name: "LMT",
                    },
                    rest: REST
                }
            },
```

**Comment by djc** [comment]
> With this release the TZDB starts to use `%z` instead of numerical time zone names such as `+01`. We have no code to handle this.
> 
> It seems to me the cleanest solution is to make the time zone name optional with the `None` case representing the special `%z`, and adding some extra code to the formatting method that uses the stuff from `FixedOffset`. What do you think?

Sounds good! Do you have time to work on this? It seems a little tricky, if I understand correctly we have to do work in chrono to make stuff in chrono-tz work correctly? But chrono-tz takes a dependency on chrono so I guess we'll need to bump chrono-tz to 0.10.0 and then also have it depend on newest chrono?

**Comment by pitdicker** [comment]
> Sounds good! Do you have time to work on this?

Yes, it doesn't seems to involved (hopefully).

**Comment by djc** [comment]
LGTM, thanks! Do you want to formally approve, since I can't?

**Comment by pitdicker** [comment]
For the formatting code it ended up to be easier to just format the integers instead of trying to make use of the offset formatting code in chrono.

The change to the `OffsetName` trait to return an `Option` makes this something that needs a version bump.

With 2024b the TZDB does switches to the `%z` format in almost all places, but skipped some. We could detect those and treat them like `%z`, but it seemed best to me to stay as close as possible to the official data.

**Comment by pitdicker** [comment]
You are quick with the review!

**Review by pitdicker — APPROVED** [review]

**Comment by pitdicker** [comment]
I'd like to push one more change. the example file should use `Option`s too.

**Comment by pitdicker** [comment]
Shall I merge and make the release?

**Comment by djc** [comment]
Yes, please!

**Comment by pitdicker** [comment]
Published :tada:.

**Pull request merged**
