### PR TITLE
tz: Update to tzdb 2022e

### PR DESCRIPTION
**Pull request by LucioFranco**

### CODE REVIEW

**Comment by djc** [comment]
The issue with regex filtering seems to be pre-existent, not sure what happened there.

Can you also add a separate commit that removes any ubuntu-18.04 from the CI config?

**Comment by LucioFranco** [comment]
Should fix the CI issues https://github.com/chronotope/chrono-tz/pull/111

**Comment by djc** [comment]
Can you rebase this?

**Comment by LucioFranco** [comment]
Should be gtg!

**Pull request merged**
